### ISSUE TITLE
I want to print Digital Signature Appearance  on last page , so how can we do it

### ISSUE THREAD

**Issue by bagojikop** [KDS/PDFsharp-netstandard20#4]

**Comment by bagojikop** [comment]
Yes its working ,    PageIndex=2

 PdfSignatureOptions options = new PdfSignatureOptions
 {
     ContactInfo = helper.ContactInfo,
     Location = helper.Location ?? "",
     Reason = $"Authorised Signature",
     Rectangle = new XRect(helper.XRect.X, Y, helper.XRect.Width, helper.XRect.Height),
    AppearanceHandler = new SignAppearanceHandler(Image, helper, pdfDocument.Pages[pdfDocument.PageCount-1]) ,
    PageIndex=2
   
    // Replace with your signature appearance handler
 };

**Comment by julienrffr** [comment]
Glad to see you've figured it out.
Closing the issue.

I know we need to add doc but I can't right now.
